# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NearTruck' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NearTruck
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Then'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'inavi-maps-sdk'

  target 'NearTruckTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NearTruckUITests' do
    # Pods for testing
  end

end
